exclude: '^(venv/|\.git/|__pycache__/|\.pytest_cache/|\.mypy_cache/|\.ruff_cache/|\.pre-commit/|build/|dist/|\.eggs/)'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=100]
      - id: ruff-format
        args: [--line-length=100]